const blueCrossHMO = {
  type: "object",
  properties: {
    "POS LW OP": { type: "string" },
  },
  additionalProperties: false,
  required: ["POS LW OP"],
};

const optum = {
  type: "object",
  additionalProperties: false,
  required: ["URN COMM IP", "URN COMM OP", "URN COMM CHD ONC OP"],
  properties: {
    "URN COMM IP": { type: "string" },
    "URN COMM OP": { type: "string" },
    "URN COMM CHD ONC OP": { type: "string" },
  },
};

const procedureSchema = {
  type: "object",
  required: [
    "LOCATION",
    "HOSPITAL CHARGE CODE",
    "CHARGE CODE DESCRIPTION",
    "REVENUE CODE",
    "CPT CODE",
    "GROSS CHARGE Effective Date 4",
    "De-identified Minimum",
    "De-identified Maximum",
    "Discounted Cash Price",
    "Blue Cross All Products IP",
    "Blue Cross HMO",
    "Blue Cross All Product FS SAT OP",
    "Blue Cross PPO LW OP",
    "Blue Cross Indem OP",
    "Harvard Pilgrim All Products IP",
    "Harvard Pilgrim LOC LW FOC OP",
    "Harvard Pilgrim LOC NAT FOC SAT OP",
    "Harvard Pilgrim NAT LW OP",
    "Harvard Pilgrim SCOAST LW OP",
    "Harvard Pilgrim SCOAST SAT OP",
    "Tufts HMO POS PPO IP",
    "Tufts CARELINK IP",
    "Tufts HMO OP",
    "Tufts POS PPO OP",
    "Tufts CARELINK OP",
    "Aetna COMM IP OP",
    "Cigna IP",
    "Cigna OP",
    "United COMM IP OP",
    "Tufts Public Plan COMM QHP IP",
    "Tufts Public Plan COMM QHP OP",
    "Allways HMO QHP IP",
    "Allways HMO QHP OP",
    "Allways PPO IP",
    "Allways PPO OP",
    "Coventry HCVM IP OP",
    "Fallon COMM IP",
    "Fallon COMM OP",
    "Humana IP OP",
    "Multiplan Clients IP OP",
    "PHCS Clients IP OP",
    "Unicare GIC IP",
    "Unicare GIC OP",
    "Beacon BMCHP (QHP) IP OP",
    "Beacon BMC (NH products) IP OP",
    "Beacon FCHP COMM IP OP",
    "Beacon GIC (Certain Products) IP OP",
    "Cigna Behavioral IP",
    "United Behavioral (Optum) IP",
    "Cigna Behavioral OP",
    "United Behavioral (Optum) OP",
    "Aetna Transplants IP",
    "Aetna Transplants OP",
    "Cigna Lifesource IP",
    "Cigna Lifesource OP",
    "Interlink Transplant IP",
    "Interlink Transplant OP",
    "LifeTrac IP",
    "LifeTrac OP",
    "Optum",
  ],
  additionalProperties: false,
  properties: {
    LOCATION: { type: "string" },
    "HOSPITAL CHARGE CODE": { type: "number" },
    "CHARGE CODE DESCRIPTION": { type: "string" },
    "REVENUE CODE": { type: "number", nullable: true },
    "CPT CODE": { type: "string" },
    "GROSS CHARGE Effective Date 4": { type: "array" },
    "De-identified Minimum": { type: "string" },
    "De-identified Maximum": { type: "string" },
    "Discounted Cash Price": { type: "string" },
    "Blue Cross All Products IP": { type: "string" },
    "Blue Cross HMO": blueCrossHMO,
    "Blue Cross All Product FS SAT OP": { type: "string" },
    "Blue Cross PPO LW OP": { type: "string" },
    "Blue Cross Indem OP": { type: "string" },
    "Harvard Pilgrim All Products IP": { type: "string" },
    "Harvard Pilgrim LOC LW FOC OP": { type: "string" },
    "Harvard Pilgrim LOC NAT FOC SAT OP": { type: "string" },
    "Harvard Pilgrim NAT LW OP": { type: "string" },
    "Harvard Pilgrim SCOAST LW OP": { type: "string" },
    "Harvard Pilgrim SCOAST SAT OP": { type: "string" },
    "Tufts HMO POS PPO IP": { type: "string" },
    "Tufts CARELINK IP": { type: "string" },
    "Tufts HMO OP": { type: "string" },
    "Tufts POS PPO OP": { type: "string" },
    "Tufts CARELINK OP": { type: "string" },
    "Aetna COMM IP OP": { type: "string" },
    "Cigna IP": { type: "string" },
    "Cigna OP": { type: "string" },
    "United COMM IP OP": { type: "string" },
    "Tufts Public Plan COMM QHP IP": { type: "string" },
    "Tufts Public Plan COMM QHP OP": { type: "string" },
    "Allways HMO QHP IP": { type: "string" },
    "Allways HMO QHP OP": { type: "string" },
    "Allways PPO IP": { type: "string" },
    "Allways PPO OP": { type: "string" },
    "Coventry HCVM IP OP": { type: "string" },
    "Fallon COMM IP": { type: "string" },
    "Fallon COMM OP": { type: "string" },
    "Humana IP OP": { type: "string" },
    "Multiplan Clients IP OP": { type: "string" },
    "PHCS Clients IP OP": { type: "string" },
    "Unicare GIC IP": { type: "string" },
    "Unicare GIC OP": { type: "string" },
    "Beacon BMCHP (QHP) IP OP": { type: "string" },
    "Beacon BMC (NH products) IP OP": { type: "string" },
    "Beacon FCHP COMM IP OP": { type: "string" },
    "Beacon GIC (Certain Products) IP OP": { type: "string" },
    "Cigna Behavioral IP": { type: "string" },
    "United Behavioral (Optum) IP": { type: "string" },
    "Cigna Behavioral OP": { type: "string" },
    "United Behavioral (Optum) OP": { type: "string" },
    "Aetna Transplants IP": { type: "string" },
    "Aetna Transplants OP": { type: "string" },
    "Cigna Lifesource IP": { type: "string" },
    "Cigna Lifesource OP": { type: "string" },
    "Interlink Transplant IP": { type: "string" },
    "Interlink Transplant OP": { type: "string" },
    "LifeTrac IP": { type: "string" },
    "LifeTrac OP": { type: "string" },
    Optum: optum,
  },
};

export const schema = {
  type: "array",
  items: procedureSchema,
};
